language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
jdk:
  - oraclejdk8
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
before_install:
  - sudo apt-get update > /dev/null
install:
  - sudo apt-get install -y --force-yes maven
  - composer install --no-dev
  - ./build/install-server.sh
  - cp src/tests/gremlin-php-script.groovy $HOME/apache-gremlin-server-3.0.0-incubating/scripts/
  - cp src/tests/gremlin-server-php.yaml $HOME/apache-gremlin-server-3.0.0-incubating/conf/
  - cp src/tests/neo4j-empty.properties $HOME/apache-gremlin-server-3.0.0-incubating/scripts/
  - cd $HOME/apache-gremlin-server-3.0.0-incubating
  - bin/gremlin-server.sh -i org.apache.tinkerpop neo4j-gremlin 3.0.0-SNAPSHOT
  - bin/gremlin-server.sh conf/gremlin-server-php.yaml
script: phpunit --bootstrap src/tests/bootstrap src/tests
